v1.2.0 release (#26)
Features
Basic README.md  #9
Adds support for direct-attached barcode scanners #23
Feature/prod operations #29

Patches
Feature/vite migration #27
Fix query logic #25
Moved database from port 8001 to 8010 #31

Issues closed:
Grouping transfer actions when assembling parts #12
Update to building with Vite framework #18
npn depreciation warnings and network failure #21
Dashboard crash after scanning an Identifier for a location into another location #22
UnboundLocalError: local variable 'identity' referenced before assignment #28

Co-authored-by: Greg Hawkridge <ghawkridge@gmail.com>